[3250][ADD] purchase_order_restriction
qrtl/axls-custom pull request #23
Opened 2023-05-04 11:26 UTC by rinaldifirdaus

[3250](https://www.quartile.co/web?db=quartile&token=dMRr78CMkEX6gyy9nTiv#id=3250&action=771&model=project.task&view_type=form&menu_id=505)

2023-05-05 04:33 UTC, yostashiro requested changes
We need to assume that users who create purchase orders are not puerchase managers, and the restriction needs to be applied as necessary right upon creation of the order. Please check and confirm the validity of my suggestions.

2023-05-05 04:33 UTC, yostashiro commented on purchase_order_restriction/readme/DESCRIPTION.rst
Fix the presentation.

![image](https://user-images.githubusercontent.com/7766939/236374809-1c5924aa-aa3c-40dc-a961-15e8a892b805.png)

2023-05-05 04:33 UTC, yostashiro commented on purchase_order_restriction/models/purchase.py
> +    )
```suggestion
    is_restricted = fields.Boolean(
        "Restrict Access",
        tracking=True,
        help="If selected, this purchase order can only be accessed by the assigned buyer or purchase managers.",
    )
    
    @api.constrains("is_restricted")
    def _check_is_restricted_access(self):
        for order in self:
            if order.user_id != self.env.user or not self.user_has_groups("purchase.group_purchase_manager"):
                raise ValidationError(_("You do not have the right to change Restric Access setting."))
```

2023-05-05 04:33 UTC, yostashiro commented on purchase_order_restriction/security/security.xml
> +    </record>
```suggestion
    <record model="ir.rule" id="purchase_order_restriction_users">
        <field name="name">View purchase orders (own or unrestricted)</field>
        <field name="model_id" ref="model_purchase_order" />
        <field name="domain_force">['|',('is_restricted','=',False),('user_id','=',user.id)]</field>
        <field name="groups" eval="[(4,ref('purchase.group_purchase_user'))]" />
    </record>
```

2023-05-05 04:33 UTC, yostashiro commented on purchase_order_restriction/security/security.xml
> +    </record>
```suggestion
    <record model="ir.rule" id="purchase_order_restriction_managers">
        <field name="name">View purchase orders (manager)</field>
        <field name="model_id" ref="model_purchase_order" />
        <field name="domain_force">[1,'=',1]</field>
        <field name="groups" eval="[(4,ref('purchase.group_purchase_manager'))]" />
    </record>
```

2023-05-05 04:33 UTC, yostashiro commented on purchase_order_restriction/views/purchase_views.xml
> +                    optional="show"
```suggestion
                    optional="hide"
```

2023-05-05 04:33 UTC, yostashiro commented on purchase_order_restriction/views/purchase_views.xml
> +                    optional="show"
```suggestion
                    optional="hide"
```

2023-05-05 04:33 UTC, yostashiro commented on purchase_order_restriction/views/purchase_views.xml
> +            </xpath>
```suggestion
            <xpath expr="//group[@name='other_info']" position="inside">
                <field name="is_restricted" />
            </xpath>
```

2023-05-05 04:33 UTC, yostashiro commented on purchase_order_restriction/views/purchase_views.xml
> +        <field name="priority">100</field>
Why this priority?
```suggestion
```

2023-05-05 17:19 UTC, rinaldifirdaus commented
@yostashiro san, i've added a new commit for this module and add some adjustment from your feedback. please kindly your review.

2023-05-06 10:20 UTC, yostashiro requested changes

2023-05-06 10:20 UTC, yostashiro commented on purchase_order_restriction/models/purchase.py
> +              by the assigned buyer or purchase managers.",
```suggestion
        help="If selected, this purchase order can only be accessed by the assigned "
        "buyer or purchase managers.",
```

2023-05-06 10:20 UTC, yostashiro commented on purchase_order_restriction/views/purchase_views.xml
> +            <xpath expr="//field[@name='date_order']" position="before">
You missed my earlier suggestion. IMO, the field does not need to be always visible as the cases where `is_restricted` needs to be selected should be limited. 

```suggestion
            <xpath expr="//group[@name='other_info']" position="inside">
```

2023-05-06 10:20 UTC, yostashiro commented on purchase_order_restriction/readme/DESCRIPTION.rst
> +* Adds Restrict Access to RFQ and Purchase Orders Tree view for Purchase Manager to monitor which records is currently restricted on the list
This explanation is too detailed and it does not add much value while it adversely adds to the maintenance cost. We should not be listing every single detail of what's included in the module.

What's important in this documentation are:

- to roughly describes what the module does, and
- to explain the reason/background why we need this module

Our audience are not really the end-users, but the people with knowledge of Odoo development, who would just grasp the implementation details by reading the code.

```suggestion
This module adds Ristrict Access boolean field in the purchase order model, to limit the
access to the purchase order to 1) the buyer and 2) purchase managers.

The module can be useful if there are orders whose conditions should not be visible to
wide range of buyers (e.g. contract rates of the temp staff).
```

2023-05-08 02:58 UTC, yostashiro approved these changes

2023-05-08 06:05 UTC, AungKoKoLin1997 approved these changes

2023-05-08 06:33 UTC, AungKoKoLin1997 commented
@rinaldifirdaus This module is not the same feature with https://github.com/OCA/purchase-workflow/tree/15.0/purchase_security? Did you check in OCA before you implemented this module or I miss something?

2023-05-08 09:48 UTC, yostashiro commented
@rinaldifirdaus Add the translation pls.

2023-05-16 09:59 UTC, yostashiro commented
Superseded by https://github.com/qrtl/axls-oca/pull/54.

2023-05-16 09:59 UTC, closed without merging