[3546][ADD] stock_lot_suffix
qrtl/axls-custom pull request #37
Opened 2023-07-12 10:02 UTC by kanda999

[3546]()

2023-07-13 12:51 UTC, yostashiro requested changes
Partial review.

2023-07-13 12:51 UTC, yostashiro commented on stock_lot_suffix/__manifest__.py
> +    "depends": ["purchase", "stock", "analytic_mixin_analytic_account"],
```suggestion
    "depends": ["purchase.stock", "analytic_mixin_analytic_account"],
```

2023-07-13 12:51 UTC, yostashiro commented on stock_lot_suffix/models/stock_picking.py
> +            lots = self.env["stock.lot"].browse(lot_ids)
`self` here is a recordset, therefore you need to loop over it.

```suggestion
        for pick in self:
            lots = self.move_line_ids.lot_id
            if lots:
```

2023-07-13 12:51 UTC, yostashiro commented on stock_lot_suffix/readme/DESCRIPTION.rst
> +This module can add a suffix to the stock_lot. The display of the name in the stock_lot changes by this module when a specific partner or analytic plan is used.
Please use the `stock.lot` nomenclature (instead of `stock_lot`) for model technical names.

2023-07-13 12:53 UTC, yostashiro commented on stock_lot_suffix/models/account_analytic_account.py
> +    is_suffix = fields.Boolean("Suffix")
Didn't we talk about making it a char field?

2023-07-14 09:46 UTC, yostashiro commented on stock_lot_suffix/models/account_analytic_account.py
> +    analytic_category = fields.Char()
The name is obscure.  I think we should name it as `lot_suffix` or something IMO.

2023-07-14 09:46 UTC, yostashiro commented on stock_lot_suffix/models/stock_lot.py
> +                new_name += analytic
```suggestion
            new_name = name[1]
            if rec.analytic_category:
                new_name += rec.analytic_category
```
A minor point.  This is a bit more readable with less LOC.

2023-07-14 09:46 UTC, yostashiro commented on stock_lot_suffix/models/stock_picking.py
> +            if lots:
Reduce the `if` ladder.

```suggestion
            if not lots:
                continue
```

2023-07-14 09:46 UTC, yostashiro commented on stock_lot_suffix/models/stock_picking.py
> +        return super()._action_done()
Can you actually consider doing this at stock.move.line level, which I think should be more simple and flexible.

2023-07-19 06:30 UTC, yostashiro commented on stock_lot_suffix/models/stock_move_line.py
> +        return super()._action_done()
```suggestion
    def _action_done(self):
        res = super()._action_done()
        for ml in self:
            if not ml.lot_id:
                continue
            vals = {}
            purchase_line = ml.move_id.purchase_line_id
            vals["channel_category"] = purchase_line.order_id.channel_category
            # We assume that there is only one analytic account with lot_suffix if any.
            vals["lot_suffix"] = purchase_line.analytic_account_ids.mapped("lot_suffix")[:1]
            ml.lot_id.write(vals)
        return res
```

2023-07-19 09:41 UTC, kanda999 commented
This will cause the test to fail, but I can do gitaggregate.

2023-07-19 10:11 UTC, yostashiro commented on stock_lot_suffix/models/stock_move_line.py
> +            vals["lot_suffix"] = lot_suffixes[0] if lot_suffixes else None
```suggestion
            analytic_account = purchase_line.analytic_account_ids.filtered(lambda x: x.lot_suffix)
            if analytic_account:
                vals["lot_suffix"] = analytic_account[0].lot_suffix
```

2023-07-19 10:11 UTC, yostashiro commented on stock_lot_suffix/models/stock_lot.py
> +        name_list = super(StockLot, self).name_get()
```suggestion
        name_list = super().name_get()
```

2023-07-19 10:11 UTC, yostashiro commented on stock_lot_suffix/models/stock_lot.py
> +                new_name += rec.lot_suffix
```suggestion
                new_name += "-" + rec.lot_suffix
```

2023-07-19 10:11 UTC, yostashiro commented on stock_lot_suffix/models/stock_lot.py
> +                new_name += rec.channel_category
```suggestion
                new_name += "-" + rec.channel_category
```

2023-07-19 10:11 UTC, yostashiro commented on stock_lot_suffix/readme/DESCRIPTION.rst
> +This module can add a suffix to the stock.lot. The display of the name in the stock.lot changes by this module when a specific partner or analytic plan is used.
The explanation doesn't sound accurate.  Please improve this.

2023-07-19 10:11 UTC, yostashiro commented on stock_lot_suffix/views/res_partner_views.xml
No need to show the field in the list view?

2023-07-19 10:11 UTC, yostashiro commented on stock_lot_suffix/models/purchase_order.py
> +            self.channel_category = channel
```suggestion
    def _onchange_partner_id(self):
        if self.partner_id:
            self.channel_category = self.partner_id.channel_category
```

2023-07-22 02:45 UTC, yostashiro commented on stock_lot_suffix/__manifest__.py
> +    "category": "",
```suggestion
    "category": "Inventory",
```

2023-07-22 02:45 UTC, yostashiro commented on stock_lot_suffix/models/stock_move_line.py
> +            # vals["lot_suffix"] = lot_suffixes[0] if lot_suffixes else None
```suggestion
```

2023-07-22 02:45 UTC, yostashiro commented on stock_lot_suffix/readme/DESCRIPTION.rst
> +This module provides the functionality to manage lot references by adding suffixes.
```suggestion
This module provides the functionality to add suffixes to the display name of lots/serials.
```

2023-07-22 02:45 UTC, yostashiro commented on stock_lot_suffix/readme/DESCRIPTION.rst
> +- When a purchase order is created using an analytic plan that the lot suffix is set.
```suggestion
Suffixes are added to lots/serials created from purchase receipts with following conditions:

- Purchase order has the channel_category set.
- Purchase order line has an analytic account with lot suffix.
```

2023-07-24 01:46 UTC, yostashiro approved these changes
Code review.

2023-07-24 02:01 UTC, merged