[16.0][3550][ADD] product_security
qrtl/axls-custom pull request #48
Opened 2023-09-28 01:38 UTC by AungKoKoLin1997

[3550](https://www.quartile.co/web#id=3550&cids=3&model=project.task&view_type=form)
Supersede of https://github.com/qrtl/axls-private/pull/37

2023-09-28 14:26 UTC, yostashiro approved these changes
Code review.  Please just update the commented part.

2023-09-28 14:26 UTC, yostashiro commented on product_security/readme/DESCRIPTION.rst
> +in the group_product_category_management group.
```suggestion
in the group_product_manager group.
```

2023-10-13 09:25 UTC, rinaldifirdaus approved these changes

2023-10-18 01:52 UTC, kanda999 requested changes

2023-10-18 01:52 UTC, kanda999 commented on product_security/i18n/ja.po
> +"プロダクトカテゴリーを更新することは許可されていません。"
```suggestion
"プロダクトカテゴリを更新することは許可されていません。"
```
Just in case, can we keep the translation the same as the standard? 
Sorry for the detail.

2023-10-18 04:31 UTC, kanda999 approved these changes

2023-10-18 04:32 UTC, merged