[3043][ADD] currency_rate_update_mizuho
qrtl/axls-custom pull request #9
Opened 2022-12-16 09:01 UTC by AungKoKoLin1997

[3043](https://www.quartile.co/web#id=3043&action=771&model=project.task&view_type=form&menu_id=505)
This module provide updating currency rate from "Mizuho japan bank". After updating currency rate using mizuho bank, the currency rate will be look like below.

<img width="1431" alt="Screen Shot 2022-12-16 at 15 24 03" src="https://user-images.githubusercontent.com/45355704/208061785-3815fbd4-5060-4f73-852d-0521022e309c.png">

This excel is the currency rate file from official mizuho bank website.
[tm_quote.csv](https://github.com/qrtl/axls-custom/files/10244209/tm_quote.csv)

2022-12-19 10:08 UTC, yostashiro requested changes

2022-12-19 10:08 UTC, yostashiro commented on currency_rate_update_mizuho/__manifest__.py
> +    "author": "Quartile Limited",
```suggestion
    "author": "Axelspace, Quartile Limited",
```

2022-12-19 10:08 UTC, yostashiro commented on currency_rate_update_mizuho/__manifest__.py
> +        "python": ["pandas"],
Please help remove pandas dependency as I believe we do not have a valid reason to use it.

- use csv.reader() instead of pd.read_csv()
- use Datetime.to_datetime() instead of pd.to_datetime

2022-12-19 10:08 UTC, yostashiro commented on currency_rate_update_mizuho/__manifest__.py
> +# Copyright 2022 Quartile Limited
```suggestion
# Copyright 2022 Axelspace
```

2022-12-19 10:08 UTC, yostashiro commented on currency_rate_update_mizuho/models/res_currency_rate_provider_mizuho.py
> +                self.content[self.date.isoformat()][currency] = rate
Do we need this part at all?

2022-12-20 03:59 UTC, AungKoKoLin1997 commented on currency_rate_update_mizuho/models/res_currency_rate_provider_mizuho.py
> +                self.content[self.date.isoformat()][currency] = rate
Yes. We need handler part.

2022-12-20 16:02 UTC, yostashiro commented
@AungKoKoLin1997 Refactored the code as XML conversion was not necessary.  Please check my update.

2022-12-21 02:35 UTC, yostashiro approved these changes

2022-12-30 16:14 UTC, merged