[4613][IMP] product_plm_import: add quality_check_categ_id for import
qrtl/axls-custom pull request #98
Opened 2024-10-31 01:32 UTC by AungKoKoLin1997

2024-11-01 02:38 UTC, yostashiro requested changes

2024-11-01 02:38 UTC, yostashiro commented on product_plm_import/wizards/product_plm_import.py
> +    ["quality_check_categ_id", "Quality Check Category", "char", False],
Following the request from the client. Never have `_id` in the variable name unless it really is an ID.

```suggestion
    ["acceptance_test_categ", "Acceptance Test Category", "char", False],
```

2024-11-01 02:38 UTC, yostashiro commented on product_plm_import/wizards/product_plm_import.py
> +                )
```suggestion
            row_dict["quality_check_categ_id"] = quality_check_categ.id
            if not quality_check_categ:
                error_list.append(
                    _("Quality Check Category (%s) does not exist.", quality_check_categ_code)
                )
```

See this: https://www.odoo.com/documentation/16.0/contributing/development/coding_guidelines.html#use-translation-method-correctly

2024-11-02 09:41 UTC, yostashiro commented on product_plm_import/models/product_plm.py
> +    def _create_product(self, quality_check_categ=False):
```suggestion
    def _create_product(self, quality_check_categ):
```

2024-11-02 09:41 UTC, yostashiro commented on product_plm_import/models/product_plm.py
> +            else False,
```suggestion
            "quality_check_categ_id": quality_check_categ.id,
```

2024-11-02 09:41 UTC, yostashiro commented on product_plm_import/models/product_plm.py
> +        return False
To make it slightly more concise, adding the missing `self.ensure_one()`.
```suggestion
        self.ensure_one()
        quality_check_categ = self.env["quality.check.category"].browse()
        test_categ = self.acceptance_test_categ
        if test_categ:
            quality_check_categ = self.env["quality.check.category"].search(
                [("code", "=", test_categ)], limit=1
            )
            if not quality_check_categ:
                self.error_message = _(
                    "Quality Check Category (%s) does not exist.", test_categ,
                )
                self.state = "failed"
        return quality_check_categ
```

2024-11-02 10:21 UTC, yostashiro reviewed
I actually don't feel comfortable with the proposed changes (doesn't current proposal override the error message?).

What I'm thinking is to improve the check mechanism at the low level:

- Cut this part into a method (`_validate_field_value()` or something): https://github.com/qrtl/axls-custom/blob/09dec36ecdd3ebcd839e9eb59370c59c2f6ee727/base_data_import/wizards/data_import.py#L121-L138
- Extend this method in `product_plm_import` to add the checking on "Acceptance Test Category", and update `row_dict` with `quality_check_categ_id` if there is a corresponding record
- Similarly, check against the product (which is currently done in `_update_vals_list`) in the extended method

The idea is to complete all the field checks within `_check_field_vals()`.  Does this make sense?

2024-11-04 10:47 UTC, yostashiro approved these changes
Code review.

2024-11-11 09:38 UTC, kanda999 approved these changes
Code and Functional review.

2024-11-12 10:10 UTC, yostashiro approved these changes
👍

2024-11-13 03:09 UTC, kanda999 approved these changes
Functional test is working.

2024-11-13 06:48 UTC, merged